components:
  schemas:

    User:
      allOf:
        - $ref: '#/components/schemas/UserWithoutIdFields'
        - type: object
          properties:
            identityId: 
              type: string
              minLength: 50
              maxLength: 53
            publicKey:
              type: string
              minLength: 10
          required:
            - identityId
            - publicKey


    UserWithoutIdFields:
      type: object
      properties:
        username:
          type: string
          minLength: 3
        registrationDate:
          type: string
          nullable: true
          format: date-time
        verifiableCredentials:
          type: array
          items:
            $ref: '#/components/schemas/VerifiableCredential'
          nullable: true
        role:
          type: string
          nullable: true
        claim:
          $ref: '#/components/schemas/Claim'
          nullable: true

    CreateUserBody:
      allOf:
        - $ref: '#/components/schemas/UserWithoutIdFields'
      
    CreateIdentityBody:
      allOf:
        - $ref: '#/components/schemas/CreateUserBody'
        - type: object
          properties:
            storeIdentity:
              type: boolean

    VerifiableCredential:
      type: object
      properties:
        '@context': 
          type: string
        id:
          type: string
          minLength: 50
          maxLength: 53
        type:
          type: array
          items:
            type: string
            minLength: 1
        credentialSubject:
            $ref: '#/components/schemas/VcSubject'
        issuer:
          type: string
          minLength: 50
          maxLength: 53
        issuanceDate: 
          type: string
          format: date-time
          minLength: 1
        proof:
          type: object
          properties:
            type: 
              type: string
              minLength: 1
            verificationMethod:
              type: string
              minLength: 1
            signatureValue:
              type: string
              minLength: 1
          required:
            - type
            - verificationMethod
            - signatureValue

    Claim:
      type: object
      properties:
        type:
          oneOf:
            - type: string
              minLength: 3
            - type: string
              enum:
                - Organization
                - Service
                - Person
                - Device
                - Product
                - Unknown

    VcSubject:
      type: object
      properties:
        id:
          type: string
          minLength: 50
          maxLength: 53
        type:
          type: string
          minLength: 1
        initiatorId:
          type: string
          minLength: 50
          maxLength: 53
      required:
        - id
        - type

    IdentityJson:
      type: object
      properties:
        doc: 
          $ref: '#/components/schemas/IdentityDocumentJson'
        key:
          $ref: '#/components/schemas/IdentityKeyPairJson'
      required:
        - doc
        - key
    
    IdentityJsonUpdate:
      allOf:
        - $ref: '#/components/schemas/IdentityJson'
        - type: object
          properties:   
            txHash:
              type: string
          required:
            - txHash
      
    IdentityDocumentJson:
      type: object
      properties:
        id: 
          type: string
        verificationMethod:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
              controller:
                type: string
              type: 
                type: string
              publicKeyBase58:
                type: string
            required:
              - id
              - controller
              - type
              - publicKeyBase58
        previousMessageId:
          type: string
        authentication:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
              controller:
                type: string
              type: 
                type: string
              publicKeyBase58:
                type: string
            required:
              - id
              - controller
              - type
              - publicKeyBase58
        created:
          type: string
          format: date-time
        updated:
          type: string
          format: date-time
        immutable:
          type: boolean
        proof:
          type: object
          properties:
            type: 
              type: string
            verificationMethod:
              type: string
            signatureValue:
              type: string
          required:
            - type
            - verificationMethod
            - signatureValue
      required:
        - id
        - authentication
        - created
        - updated
        - immutable
        - proof
    
    IdentityKeyPairJson:
      type: object
      properties:
        type:
          type: string
        public:
          type: string
        secret: 
          type: string
        encoding:
          type: string
          enum:
            - base16
            - base58
            - base64
      required:
        - type
        - public
        - secret
        - encoding
