apiVersion: apps/v1
kind: Deployment
metadata:
  name: ensuresec-api
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: ensuresec-api
  template:
    metadata:
      labels:
        app: ensuresec-api
    spec:
      containers:
      - image: mastrogiovanni/e-commerce-tools:latest
        env:
        - name: PORT
          value: "3000"
        - name: API_VERSION
          value: v1
        - name: DATABASE_NAME
          value: admin
        - name: NETWORK
          value: main
        - name: EXPLORER
          value: https://explorer.iota.org/mainnet/transaction
        - name: IOTA_PERMA_NODE
          value: https://chrysalis-chronicle.iota.org/api/mainnet/
        - name: DATABASE_URL
          value: "mongodb://username:password@mongodb-service.default.svc.cluster.local:27017/test?authSource=admin&readPreference=primary&appname=ensuresec&ssl=false"
        - name: IOTA_HORNET_NODE
          value: "http://hornet.default.svc.cluster.local:14265"
        - name: SERVER_SECRET
          value: "PpKFhPKJY2efTsN9VkB7WNtYUhX9Utaa"
        - name: SERVER_IDENTITY
          value: "did:iota:6WGPSFrJxEKk6PCYFdckAobgquRBQR3KK8AHUgnFVNRf"
        - name: "SERVER_IDENTITY"
          value: "did:iota:4cgjGuF3Czp5HUSKCuxKa2wzVPaLiZvLChhBH4SJVE1X"
        - name: "API_KEY"
          value: "94F5BA49-12B6-4E45-A487-BF91C442276D"
        name: ensuresec-api
        ports:
        - protocol: TCP
          containerPort: 3000
        volumeMounts:
        - mountPath: /data/db
          name: db
      volumes:
      - name: db
        emptyDir: {}

