apiVersion: v1
kind: Service
metadata:
  name: audit-trail-gw-ms
spec:
  selector:
    app: audit-trail-gw-ms
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002
---
apiVersion: v1
kind: Service
metadata:
  name: ssi-bridge-ms
spec:
  selector:
    app: ssi-bridge-ms
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001