apiVersion: configuration.konghq.com/v1
kind: KongClusterPlugin
metadata:
  name: rl-by-ip
  annotations:
    kubernetes.io/ingress.class: kong
  labels:
    global: "true"
config: 
  minute: 70
  hour: 10000
  policy: local
  fault_tolerant: true
  hide_client_headers: false
  redis_ssl: false
  redis_ssl_verify: false
plugin: rate-limiting