version: '3.7'
services:
  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_DATABASE: ${DATABASE_NAME}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - 27017:27017
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - mongodb_data_container:/data/db

  initialize-job:
    build: .
    environment:
      PORT: 3000
      DATABASE_NAME: ${DATABASE_NAME}
      IOTA_HORNET_NODE: ${IOTA_HORNET_NODE}
      IOTA_PERMA_NODE: ${IOTA_PERMA_NODE}
      DATABASE_URL: ${DATABASE_URL}
      SERVER_SECRET: ${SERVER_SECRET}
    restart: on-failure
    command: node dist/index.js setup-api
    depends_on: 
      - mongo

  audit-trail-gw:
    build:
      dockerfile: Dockerfile-audit-trail-gw
      context: ./
    environment: 
      DATABASE_NAME: ${DATABASE_NAME}
      IOTA_HORNET_NODE: ${IOTA_HORNET_NODE}
      IOTA_PERMA_NODE: ${IOTA_PERMA_NODE}
      DATABASE_URL: ${DATABASE_URL}
      SERVER_SECRET: ${SERVER_SECRET}
    restart: always
    depends_on: 
      - mongo
      - initialize-job
    ports:
      - 3000:3000

  ssi-bridge:
    build:
      dockerfile: Dockerfile-ssi-bridge
      context: ./
    environment: 
      DATABASE_NAME: ${DATABASE_NAME}
      IOTA_HORNET_NODE: ${IOTA_HORNET_NODE}
      IOTA_PERMA_NODE: ${IOTA_PERMA_NODE}
      DATABASE_URL: ${DATABASE_URL}
      SERVER_SECRET: ${SERVER_SECRET}
    restart: always
    depends_on: 
      - mongo
      - initialize-job
    ports:
      - 3001:3000

volumes:
  mongodb_data_container: