version: '3.7'
services:
  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
  ensuresec_api:
    build: .
    environment: 
      PORT: 3000
      API_VERSION: v1
      DATABASE_NAME: e-commerce-audit-log
      IOTA_PERMA_NODE: https://nodes.iota.org:443
      NETWORK: main
      EXPLORER: https://explorer.iota.org/mainnet/transaction
    depends_on: 
      - mongodb_container
    ports:
      - 3000:3000
volumes:
  mongodb_data_container:
