version: '3.7'
services:
  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_DATABASE: ${DATABASE_NAME}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - 27017:27017
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - mongodb_data_container:/data/db
  
  traefik:
    image: "traefik:v2.6"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  initialize-audit-trail:
    build:
      dockerfile: Dockerfile-audit-trail-gw
      context: ./
    environment:
      PORT: 3002
      DATABASE_NAME: ${DATABASE_NAME}
      IOTA_HORNET_NODE: ${IOTA_HORNET_NODE}
      IOTA_PERMA_NODE: ${IOTA_PERMA_NODE}
      DATABASE_URL: ${DATABASE_URL}
      SERVER_SECRET: ${SERVER_SECRET}
    restart: on-failure
    command: node dist/index.js setup-api
    depends_on: 
      - mongo
      - traefik

  audit-trail-gw:
    build:
      dockerfile: Dockerfile-audit-trail-gw
      context: ./
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.audittrailgw.entrypoints=web"
      - "traefik.http.routers.audittrailgw_ch.rule=PathPrefix(`/api/v0.1/channels`)"
      - "traefik.http.routers.audittrailgw_ci.rule=PathPrefix(`/api/v0.1/channel-info`)"
      - "traefik.http.routers.audittrailgw_sub.rule=PathPrefix(`/api/v0.1/subscriptions`)"
    environment: 
      PORT: 3002
      DATABASE_NAME: ${DATABASE_NAME}
      IOTA_HORNET_NODE: ${IOTA_HORNET_NODE}
      IOTA_PERMA_NODE: ${IOTA_PERMA_NODE}
      DATABASE_URL: ${DATABASE_URL}
      SERVER_SECRET: ${SERVER_SECRET}
    restart: always
    depends_on: 
      - mongo
      - initialize-audit-trail
      - traefik
    ports:
      - 3002:3002

  initialize-ssi-bridge:
    build:
      dockerfile: Dockerfile-ssi-bridge
      context: ./
    environment:
      PORT: 3001
      DATABASE_NAME: ${DATABASE_NAME}
      IOTA_HORNET_NODE: ${IOTA_HORNET_NODE}
      IOTA_PERMA_NODE: ${IOTA_PERMA_NODE}
      DATABASE_URL: ${DATABASE_URL}
      SERVER_SECRET: ${SERVER_SECRET}
    restart: on-failure
    command: node dist/index.js setup-api
    depends_on: 
      - mongo
  
  ssi-bridge:
    build:
      dockerfile: Dockerfile-ssi-bridge
      context: ./
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ssibridge.entrypoints=web"
      - "traefik.http.routers.ssibridge_id.rule=PathPrefix(`/api/v0.1/identities`) "
      - "traefik.http.routers.ssibridge_auth.rule=PathPrefix(`/api/v0.1/authentication`)"
      - "traefik.http.routers.ssibridge_ver.rule=PathPrefix(`/api/v0.1/verification`)"
    environment: 
      PORT: 3001
      DATABASE_NAME: ${DATABASE_NAME}
      IOTA_HORNET_NODE: ${IOTA_HORNET_NODE}
      IOTA_PERMA_NODE: ${IOTA_PERMA_NODE}
      DATABASE_URL: ${DATABASE_URL}
      SERVER_SECRET: ${SERVER_SECRET}
    restart: always
    depends_on: 
      - mongo
      - initialize-ssi-bridge
      - traefik
    ports:
      - 3001:3001

volumes:
  mongodb_data_container: