version: '3.7'
services:
  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_DATABASE: ${DATABASE_NAME}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - 27017:27017
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - mongodb_data_container:/data/db

  initialize-job:
    build: .
    environment:
      PORT: 3000
      DATABASE_NAME: ${DATABASE_NAME}
      IOTA_HORNET_NODE: ${IOTA_HORNET_NODE}
      IOTA_PERMA_NODE: ${IOTA_PERMA_NODE}
      DATABASE_URL: ${DATABASE_URL}
      SERVER_SECRET: ${SERVER_SECRET}
    restart: on-failure
    command: node dist/index.js setup-api
    depends_on: 
      - mongo
  
  traefik:
    image: "traefik:v2.6"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  whoami:
    image: "traefik/whoami"
    container_name: "simple-service"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.localhost`)"
      - "traefik.http.routers.whoami.entrypoints=web"

  audit-trail-gw:
    build:
      dockerfile: Dockerfile-audit-trail-gw
      context: ./
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.localhost`)"
      - "traefik.http.routers.whoami.entrypoints=web"
    environment: 
      PORT: 3000
      DATABASE_NAME: ${DATABASE_NAME}
      IOTA_HORNET_NODE: ${IOTA_HORNET_NODE}
      IOTA_PERMA_NODE: ${IOTA_PERMA_NODE}
      DATABASE_URL: ${DATABASE_URL}
      SERVER_SECRET: ${SERVER_SECRET}
    restart: always
    depends_on: 
      - mongo
      - initialize-job
      - traefik
      - whoami
    ports:
      - 3000:3000

  ssi-bridge:
    build:
      dockerfile: Dockerfile-ssi-bridge
      context: ./
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.localhost`)"
      - "traefik.http.routers.whoami.entrypoints=web"
    environment: 
      PORT: 3001
      DATABASE_NAME: ${DATABASE_NAME}
      IOTA_HORNET_NODE: ${IOTA_HORNET_NODE}
      IOTA_PERMA_NODE: ${IOTA_PERMA_NODE}
      DATABASE_URL: ${DATABASE_URL}
      SERVER_SECRET: ${SERVER_SECRET}
    restart: always
    depends_on: 
      - mongo
      - initialize-job
      - traefik
      - whoami
    ports:
      - 3001:3001

volumes:
  mongodb_data_container: