name: Publish client-sdk to npmjs
on:
  push:
      branches: [ develop ]
      paths: 
        - "clients/client-sdk/**"
        - ".github/workflows/publish-node-sdk-npmjs.yml"
  workflow_dispatch:
env:
  PACKAGE_JSON: ""
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      # build local package in advance
      - run: |
          cd api/shared-modules
          npm install
          npm run build
      - run: cd clients/client-sdk && npm ci
      - run: cd clients/client-sdk && npm run build
      - run: |
            echo '$PACKAGE_JSON<<EOF' >> $GITHUB_ENV
            cat ./package.json >> $GITHUB_ENV
            echo 'EOF' >> $GITHUB_ENV
      - name: Stable version
        if: ${{!contains(fromJson(env.PACKAGE_JSON).version, 'alpha')}}
        run: cd clients/client-sdk && npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Pre-release version
        if: ${{contains(fromJson(env.PACKAGE_JSON).version }}, 'alpha')}}
        run: cd clients/client-sdk && npm publish --tag next --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}