name: deploy

on:
  pull_request:
    branches: [docs/addTestAndDeployAction]
  push:
    branches: [docs/addTestAndDeployAction]

jobs:
  checks:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Test Build
        run: |
          cd documentation
          if [ -e package-lock.json ]; then
          npm ci
          else
          npm i
          fi
          npm run setup
          cd local-wiki/iota-wiki
          yarn
          cd ../../
          npm test
  gh-release:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: |
          cd documentation
          if [ -e package-lock.json ]; then
          npm ci
          else
          npm i
          fi
      - name: Setup Wiki
        run: |
          npm run setup
          cd local-wiki/iota-wiki
          yarn
          cd ../../
      - name: Build Wiki
        run: |
          npm test
      - name: Release to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./local-wiki/iota-wiki/build

